import { Navbar } from "@/components/Layout/Navbar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
